anarock/pebble

src/components/Button.tsx
src/components/Sidebar.tsx
src/components/__tests__/__snapshots__/button.test.tsx.snap
src/components/__tests__/__snapshots__/popper.test.tsx.snap
src/components/styles/Button.styles.ts
src/components/styles/Sidebar.styles.ts
src/theme/styles.ts

feat(sidebar): disable overflow of body when sidebar is open

---

src/components/Toast.tsx

in case multiple toasts are fired, the last toast should be visible for at least 2000ms.

fix(toast): show latest toast only.

---

src/components/Input.tsx
src/components/Select.tsx
src/components/__tests__/__snapshots__/select.test.tsx.snap
src/components/styles/Input.styles.ts
src/components/styles/Select.styles.ts
src/components/typings/Input.ts
stories/select.story.tsx

https://gallery.io/projects/MCHbtQVoQ2HCZT4mqWZoe47O/files/MCHtA7U1iMGr6_t5bV_53j4SjSutDL__KP4
The input color is gray.darker
Wanted to leave functionality as is (i.e. readonly), so made Input accept inputClassName prop.
Avoid using `&.className` in emotion as difficult to override and requires string matching code which cannot be type checked.

Match Select Design as per Styleguide

---

Readme.md
scripts/templates/pebble-css.hbs
src/components/styles/Calendar.styles.ts
src/components/styles/Search.styles.ts
stories/radio.story.tsx

Changed `box-sizing:border-box` from * to  using inherit.
https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
Also Jekin said to use SF instead of Roboto for fallback font.

Fix some box-sizing and other stuff

---

src/components/Search.tsx
src/components/__tests__/search.test.tsx
src/components/shared/OptionGroup.tsx
src/components/typings/OptionGroup.ts
src/components/typings/Select.ts
stories/optionGroupCheckBox.story.tsx
stories/search.story.tsx

Fixes https://github.com/ritz078/pebble/pull/146/files

Fixes Docu Element and onChange is not a function

---

package.json
src/components/shared/OptionGroup.tsx

reverting the changes made in OptionGroup.tsx in this PR:
https://github.com/ritz078/pebble/commit/0bd58481b9d4a9d8c1b10055a7b144edb55077bf#diff-fdcb45392aa3abaf12c0821f35dbe197

revert handleKeyPress changes

---

src/components/Option.tsx
src/components/__tests__/__snapshots__/checkbox.test.tsx.snap
src/components/__tests__/__snapshots__/option.test.tsx.snap
src/components/__tests__/__snapshots__/radio.test.tsx.snap
src/components/__tests__/select.test.tsx
src/components/shared/Control.tsx
src/components/styles/Control.styles.ts
src/components/styles/Options.styles.ts
src/components/typings/Option.ts
stories/option.story.tsx
stories/radio.story.tsx

See the `<Option />` and `<Radio />` components on now to see the changes.

Wrap Option Label and Left Align Radio

---

src/components/DropDown.tsx
src/components/__tests__/__snapshots__/phonenumberinput.test.tsx.snap
src/components/__tests__/__snapshots__/select.test.tsx.snap
src/components/__tests__/__snapshots__/timepicker.test.tsx.snap
src/components/styles/Dropdown.styles.ts

Reduced one `<div>` and set `position: relative` by default because we had to set it on every instancee of DropDown.

Dropdown Styles position relative

---

src/components/Modal.tsx
src/components/styles/Modal.styles.ts
src/components/styles/PopUp.styles.ts

More Modal Changes

---

src/components/Sidebar.tsx
stories/sidebar.story.tsx

Remove disableScrollY when Sidebar unmounts

Sidebar Remove Body Class on Unmount

---

src/utils/animation.ts
yarn.lock

This should have been an issue but thought better to get it fixed in a PR.

Fix Now Build, (Update react-spring version, types)

---

src/utils/analytics/ga.ts

GA not working in prod. Sorry, my bad.

Need to use window.ga

---

package.json
src/components/Calendar.tsx
src/components/DateInput.tsx
src/components/__tests__/calendar.test.tsx
src/components/typings/Calendar.ts
src/components/typings/DateInput.ts
src/components/typings/PresetCalendar.ts
stories/calendar.story.tsx
yarn.lock

@ritz078 My local build is working, can you tell me what is the error on now.

Improve Calendar Typings

---

src/components/Text.tsx
src/components/__tests__/__snapshots__/text.test.tsx.snap
src/components/__tests__/text.test.tsx
src/components/index.ts
src/components/typings/Text.ts
src/theme/typings/typography.ts
stories/text.story.tsx

Usage:
```jsx
import { Text, typography } from "@anarock/pebble"
<Text typography={typography.xl.normal}></Text>
```

feat(Text): added a new Text component

---

packages/pebble-web/src/components/Tooltip.tsx

Kudos to @ritz078 
https://stackoverflow.com/questions/4258615/what-is-the-difference-between-jquerys-mouseout-and-mouseleave

mouseout -> mouseleave

---

packages/pebble-web/jest.config.js
packages/pebble-web/package.json
packages/pebble-web/src/components/Popper.tsx

The tree shaking tests were not run

Fix Tree Shaking Tests

---

packages/pebble-shared/package.json

Which cannot be said to be side effect free.

Pebble Shared exports styles

---

packages/pebble-web/src/components/TimePicker.tsx
packages/pebble-web/src/components/__tests__/__snapshots__/timepicker.test.tsx.snap

- fix `0` value state
- format hour, minute selected value

Timepicker: ui fix

---

packages/pebble-web/src/components/Slider.tsx
packages/pebble-web/src/components/typings/Slider.ts
packages/pebble-web/stories/slider.story.tsx

- `required`
- default label extractor
- values were being set to undefined

Slider component fixes

---

packages/pebble-web/src/components/Rating.tsx
packages/pebble-web/src/components/__tests__/rating.test.tsx
packages/pebble-web/src/components/index.ts
packages/pebble-web/src/components/styles/Rating.styles.ts
packages/pebble-web/src/components/typings/Rating.ts
packages/pebble-web/stories/rating.story.tsx

- design: https://www.figma.com/file/6atJwNCeaF6vnJ4mIcHaWu/Design-System-in-Dev

Rating component

---

packages/pebble-shared/stories/icons.story.tsx

https://icon-search--5cb6f92366a0080020cba496.chromatic.com/?path=/story/theme-icons--list

add icon search

---

packages/pebble-web/src/components/DateInput.tsx
packages/pebble-web/src/components/styles/Date.styles.ts
packages/pebble-web/src/components/typings/DateInput.ts
packages/pebble-web/stories/input.story.tsx

https://dateinput-error--5cb6f92366a0080020cba496.chromatic.com/?path=/story/components-input--date

error message prop for dateInput

---

packages/pebble-web/src/utils/animation.ts

https://animation-duration--5cb6f92366a0080020cba496.chromatic.com?path=/story/components-toast--default

increase leave animation duration

---

packages/pebble-web/src/components/Sidebar.tsx
packages/pebble-web/src/components/styles/Sidebar.styles.ts

https://sidebar-transition--5cb6f92366a0080020cba496.chromatic.com/?path=/story/components-sidebar--simple

sync sidebar with animation constants

---

packages/pebble-web/src/components/Sidebar.tsx

> **Warning**
> additional css changes might be required to fix sidebar content size

Sidebar height

---

packages/pebble-web/src/components/DateInput.tsx

this change was originally added in #427 but got lost in merge conflicts

remove DateInput placeholder suffix
